### ISSUE TITLE
Question about battery usage

### ISSUE THREAD

**Issue by Krankenkasse** [alexander-toch/nrf52840-playground#3]
Hey! Before I start building my own e-paper display I'd like to know 

> for how long can you run your display without recharging

> how often do you update the data on the screen?

Thank you very much for your code!!

**Comment by alexander-toch** [comment]
Hey!

The display has been running for five months now, and the battery is currently at 3.5V, so it should still run for a few additional months 🤞

The refresh interval is 5 minutes.

**Comment by Krankenkasse** [comment]
Thank you!!
